### ISSUE TITLE
"Multiple Lua VMs detected "

### ISSUE THREAD

**Issue by drriguz** [diegonehab/luasocket#106]
I build luasocket3.0-rc1 on windows via MinGW64 + lua5.2.3(also build with MinGW64) on Win8X64 bit.
When I run a simple script (just contains http = require("socket.http")), it says:
lua: multiple Lua VMs detected
stack traceback:
    [C]: in ?
    [C]: in function 'require'
    D:\Lite\lua\lua\socket.lua:12: in main chunk
    [C]: in function 'require'
    D:\Lite\lua\lua\socket\http.lua:10: in main chunk
    [C]: in function 'require'
    listMv.lua:1: in main chunk
    [C]: in ?

> Exit code: 3221226356
> here is my lua folder:
> │  lua.exe
> │  luac.exe
> ├─include
> │      lauxlib.h
> │      lua.h
> │      lua.hpp
> │      luaconf.h
> │      lualib.h
> ├─lib
> │      liblua.a
> ├─lua
> │  │  ltn12.lua
> │  │  mbox.lua
> │  │  mime.lua
> │  │  socket.lua
> │  └─socket
> │          ftp.lua
> │          headers.lua
> │          http.lua
> │          smtp.lua
> │          tp.lua
> │          url.lua
> ├─mime
> │      core.dll
> └─socket
>         core.dll
> Looking forward for your reply.

**Comment by DenisKolodin** [comment]
Thank you, siffiejoe! It works)
