### ISSUE TITLE
socket.select() return value documentation

### ISSUE THREAD

**Issue by okroth** [diegonehab/luasocket#118]
According to the reference manual socket.select() returns an error message as third value which shall be "timeout" for a timed out select() operation and nil otherwise.
In fact, select() does return the string "error" (up to version 2.0.2) respectively "select failed" (version 3.0).
This discrepancy leads to undesired behaviour with copas.step(), which throws an error when it comes across this.

**Comment by diegonehab** [comment]
I fixed the documentation to mention "select failed". This is, indeed, an error. The other scenarios were already in the docs.
