### ISSUE TITLE
SSL is not handled properly during URL redirection

### ISSUE THREAD

**Issue by gokceneraslan** [diegonehab/luasocket#120]
If `http.request` encounters an https URL during HTTP 301 redirection, it keeps requesting the same page over and over until it hits redirection limit which is 5.

In the following code, requested URL points to an https URL through a 301 message which in turn leads to a loop where the same https page is requested 4 times. request call should either handle SSL/TLS (which would be quite amazing since luasec does not support `redirect` argument) or return an error message gracefully.

```lua
http = require "socket.http"
ltn12 = require "ltn12"

respbody = {}
one, code, head = http.request{url="http://www.itusozluk.com/image/sozluk-yazarlarinin-tipleri_517617.jpg",
                               sink = ltn12.sink.table(respbody),
                               redirect=true}

print("done")
print(table.concat(respbody))
print(code)
```
The error is more clear when some `print` lines are added to `shouldredirect` function in `http.lua` file.

**Comment by diegonehab** [comment]
Sorry for the delay. Fixed this.
