### ISSUE TITLE
LR install and Lua 5.3

### ISSUE THREAD

**Issue by andrewstarks** [diegonehab/luasocket#123]
I'm attempting to install luasocket using luarocks on a Lego EV3. I've got Lua 5.3.

It downloads, compiles and installs without warning. However:
```lua
Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> socket = require'socket'
error loading module 'socket.core' from file '/usr/local/lib/lua/5.3/socket/core.so':
	/usr/local/lib/lua/5.3/socket/core.so: undefined symbol: luaL_checkint
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.3/socket.lua:12: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
```

luarocks *seems* correctly configured for Lua 5.3. An attempt to install `lpeg` is successful (installs, and runs correctly).

luasocket is being installed into `/usr/libs/lua/5.3/[etc]`.

So I will attempt to fix this myself. I just thought I'd report the error here, since it may affect anyone attempting an LR install of luasocket.

Thanks!

-Andrew

**Comment by siffiejoe** [comment]
I think you already reported this in #122.

There *is* no symbol `luaL_checkint` in Lua 5.3 any more. `luaL_checkint` is provided as a macro if `LUA_COMPAT_APIINTCASTS` is `#define`d when including `lauxlib.h`, so the correct fix would be to add this define to LuaSocket's rockspec or to replace the `luaL_checkint` in the LuaSocket source.

As a quick and dirty fix you could set `variables.CC = "gcc -DLUA_COMPAT_APIINTCASTS"` in your LuaRocks config file.

**Comment by andrewstarks** [comment]
That is embarrassing. I'm sorry about the duplicate. I don't get to use luarocks normally and hadn't even considered checking for a prior issue, beyond the front page. 

I've made this patch in my luasocket and did not attempt to make a pull request from it (I think). I'll do my homework now. :P

Again, please accept my apology for the noise.
