### ISSUE TITLE
LuaJIT: Symbol not found: _luaL_prepbuffsize

### ISSUE THREAD

**Issue by mesca** [diegonehab/luasocket#126]
I have the following error with LuaJIT (everything is fine with Lua 5.2.3):
```
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> require "socket"
error loading module 'socket.core' from file '/usr/local/lib/lua/5.2/socket/core.so':
	dlopen(/usr/local/lib/lua/5.2/socket/core.so, 6): Symbol not found: _luaL_prepbuffsize
  Referenced from: /usr/local/lib/lua/5.2/socket/core.so
  Expected in: dynamic lookup

stack traceback:
	[C]: at 0x010002cfa0
	[C]: in function 'require'
	/usr/local/share/lua/5.2/socket.lua:12: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x0100001c70
```

Luasocket was installed with:
```
luarocks install luasocket --only-server=http://luarocks.org/repositories/rocks-scm
```

Any suggestion?

**Comment by diegonehab** [comment]
If I recall correctly, LuaJit is for Lua 5.1...

**Comment by mesca** [comment]
Thanks for your answer. I was wondering if something could be done on Luasocket's side to stay compatible, but if not I will revert to 5.1. In my case JIT is more important than 5.2.

**Comment by diegonehab** [comment]
This is no a LuaSocket problem. It's LuaJIT that is not compatible with Lua 5.2. So if you compile LuaSocket for Lua 5.2, how is it going to work with LuaJIT? You need to compile a version of LuaSocket for Lua 5.1 and then you can use it with LuaJIT.

**Comment by mesca** [comment]
Understood. Thanks!
