### ISSUE TITLE
inet_global_getaddrinfo leaks resolved if getnameinfo fails

### ISSUE THREAD

**Issue by harningt** [diegonehab/luasocket#127]
In the function inet_global_getaddrinfo in inet.c, getaddrinfo allocates resolved on line 174.
Line 210 is where it is freed.

Line 210 is never reached if getnameinfo (on line 183) fails, causing an early return at line 188.

A quick fix would be to add an additional freeaddrinfo before the early exit.

**Comment by diegonehab** [comment]
Thanks! Fixed.
