### ISSUE TITLE
expose compile time constants

### ISSUE THREAD

**Issue by Tieske** [diegonehab/luasocket#129]
Some compile time constants, such as the max UDP datagram size should be exposed on the lua side to know the details of the lib at runtime.

**Comment by diegonehab** [comment]
Do we have a better solution to this issue? In IPv6, we could have very large datagrams. Allocating a large buffer in the t_udp structure seems wasteful. How about we add a number argument to the udp creation function stating the size of the maximum datagram that the user will ever try to receive? Then, if it is larger than 8k, we allocate a buffer of the correct size and attach it to the t_udp structure. If it is smaller than 8k, we keep using the stack frame as we are now doing.

**Comment by Tieske** [comment]
Sorry, you lost me. The PR only exposes values used (as set at compile time) to Lua, so Lua code can check with what files LuaSocket was compiled. It doesn't allow changing them from Lua.

**Comment by Tieske** [comment]
I think my original issue text should have said "exposed as read only on the Lua side" to make my intent clearer.

**Comment by diegonehab** [comment]
I know. But improves a bit on a problem that has existed for a long time. I.e., LuaSocket has a limited datagram size for receiving packages with udp. I think we should fix the underlying problem. :)

**Comment by Tieske** [comment]
Right. In that case I agree that your proposal seems the best solution. But then it would also need to expose a method to retrieve the datagram size from a specific socket.

**Comment by diegonehab** [comment]
Yes. I agree. I will leave this open and at some point implement this. I'll be away for a couple weeks but these days I've had some time to work on LuaSocket. :)

**Comment by Tieske** [comment]
for reference; it is needed for non-blocking reads, as implemented here;
https://github.com/keplerproject/copas/blob/49722e9e53a0a2009e8c119c8f4ca14a15c3c8a1/src/copas/copas.lua#L149-L163

**Comment by diegonehab** [comment]
I just pushed a branch [arbitrary-datagram](/github/diegonehab/tree/arbitrary-datagram) that purports to fix this. Can you take a look and see if it closes the issue with advantage?

**Comment by Tieske** [comment]
sorry for the lame responses, we're all to busy, and I know all too well how much it sucks when you put in an effort and nobody takes the time to respond. Thanks a lot for your continuing effort on LuaSocket. :+1:

**Comment by diegonehab** [comment]
Don't worry! :) I know I haven't been as responsive as I could.
