### ISSUE TITLE
URL parsing fails

### ISSUE THREAD

**Issue by Tieske** [diegonehab/luasocket#135]
```lua
local url = require("socket.url")

local default = {
    host = "",
    port = 80,
    path ="/",
    scheme = "http"
}

local u = url.parse("http://www.google.com", default)
assert(u.scheme == "http")
assert(u.host == "www.google.com")
assert(u.path == "/")
local u = url.parse("www.google.com/hello/there", default)
assert(u.scheme == "http")
assert(u.path == "www.google.com/hello/there", u.path)      --> this passes
assert(u.host == "www.google.com", u.host)                  --> this fails
````
The second parse above, leaves out the scheme. Then the host part ends up in the path field.

as long as the hostname starts with `//` it works. But if this is left out, then the `path` part seems to have a higher presedence than the `host` part.
I would have  expected that anything before the first `/` would be the host, and the `path` would be anything after that first `/`.

It's not that hard to fix, but I'm not certain that it is an error, or a bad understanding of how url's are supposed to work on my part.

**Comment by Tieske** [comment]
The above makes
```lua
x = http.request("www.google.com")
````
Fail with an `Invalid host` error message.

**Comment by diegonehab** [comment]
Take a look at http://www.ietf.org/rfc/rfc2396.txt appendix A (Collected BNF for URI
). I think LuaSocket's interpretation is correct, no? If you don't add a //, then the correct interpretation is a path, not a host.

**Comment by Tieske** [comment]
you're right. But the `invalid host` error is akward. But not sure how/where to resolve this.

Seems tempting for `http.request` to test for either `http://` or `https://` before parsing the url. And if not found insert `http://`.
But I'm not sure whether that type of defaults fits every scenario.

**Comment by diegonehab** [comment]
When in doubt, I try to follow the RFC and avoid trying to be smart. I think most people got used to typing host names directly on the location bar of browsers. It's natural that programmers would do the same. But programmers can add this smartness as part of the application.

**Comment by Tieske** [comment]
agreed :+1:
