### ISSUE TITLE
Timeout on socket.dns.toip()

### ISSUE THREAD

**Issue by thefosk** [diegonehab/luasocket#137]
Is it possible to set a timeout on `socket.dns.toip()` ?

**Comment by diegonehab** [comment]
Not really. You'd need an external library for that. LuaSocket uses POSIX calls and they do not support timeout.

**Comment by JasperBRiedel** [comment]
You could try running the method "socket.dns.toip()" in another thread, and if the timeout is reached just kill the thread. Of course you'd then need another library for some kind of thread implementation. Not sure if it helps, Just an idea I had....
