### ISSUE TITLE
How to download file by using luasocket ?

### ISSUE THREAD

**Issue by quiloos39** [diegonehab/luasocket#143]
I would like to know how ?

**Comment by diegonehab** [comment]
This question is too abstract as formulated. There are many different ways to answer.

**Comment by quiloos39** [comment]
Like i want to download zip file from site and save it to my current folder.

Eg: www.lua.org/ftp/lua-5.3.1.tar.gz download this file and save it to current folder.

**Comment by diegonehab** [comment]
This is covered in the manual (HTTP). Also look into etc/get.lua.
