### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by vesameskanen** [diegonehab/luasocket#144]
Dear Mr. Nehab,

In the past, I have used Lua successfully for multithreaded server architecture, where each thread runs in its own Lua state, and some memory demanding resources (created in a C lib, accessed as userdata) are kept in shared memory  and used by all threads.  Server IO is done using lua-socket; while I know that lua-socket is not guaranteed to be thread safe, its debian package version 2.0.2-8  worked fairly well,  and crashes were really rare.

However, after installing Jessie with lua-socket 3.0~rc1-3, socket IO become totally unstable in multithreaded execution. Lua segfaults or crashes instantly by various memory corruption issues.

Would it be possible to develop lua-socket  towards thread-safety?  In my opinion, absence of basic IO features under multithreading cripples otherwise promising possibility to use Lua in performance critical applications requiring use of multiple cores, provided by modern computers.

Thank you for your valuable work!

Vesa Meskanen

**Comment by istr** [comment]
Maybe you should consider migrating your server infrastructure to [OpenResty](http://openresty.org/) where you have what you want:
- shared resources
- pre-loaded modules / libraries
- configurable worker-threads
- modern and high performance (socket) IO using coroutines

On top of that:
- [LuaJIT](http://luajit.org/)
- lots of additional data-bindings

Just an idea... Nowadays OpenResty could be considered battle proven and stable

**Comment by vesameskanen** [comment]
Thanks for an interesting link! OpenResty seems to be worth knowing even if it it would not solve my current problem conveniently. 

Currently I solved the problem by placing all http and socket.connect calls behind a mutex lock. Luckily, socket select, send and receive seem to work OK asynchronously. This is a decent solution as my service is mainly computation, not IO, intensive.

**Comment by diegonehab** [comment]
So long as there is a single thread accessing a socket, you should be fine. Is there a good scenario where you'd need multiple threads calling socket functions on the same socket object?

**Comment by siffiejoe** [comment]
At least the following POSIX functions used by LuaSocket are not required (by POSIX) to be thread-safe:
*   strerror
*   gethostbyaddr
*   gethostbyname
*   inet_ntoa

**Comment by vesameskanen** [comment]
It is indeed not sensible to use the same socket from several threads simultaneously :) In my server architecture, each thread (they are worker threads serving separate clients) uses its own socket.

**Comment by diegonehab** [comment]
Then the problem is most likely in the use of non-threadsafe POSIX functions. Connect should be threadsafe except for the strerror functions, right?

**Comment by siffiejoe** [comment]
I believe so. `gai_strerror` is thread-safe in GLIBC (but not on Windows), `inet_ntoa` is as well (the GLIBC-version uses thread-local storage). `gethostbyaddr` and `gethostbyname` are not called from `connect`, and `getaddrinfo`/`freeaddrinfo` are thread-safe. POSIX has `strerror_r` as a thread-safe replacement for `strerror` (but that will require some code changes). The usual socket functions (`socket`, `connect`, `bind`, `accept`, etc.) are all thread-safe.

**Comment by vesameskanen** [comment]
I did some further testing to see where the problem could be. Again, I noticed that only socket.connect and http calls seemed to cause failures. To be exact, my setup is lua 5.1.5, debian jessie and lua-socket 3.0~rc1-3, which I compiled with debugging information. At the end of this message is a backtrace of a typical crash.

Interestingly, I noticed that when I built a bsd version of lua 5.1.5 for debugging purposes, by linking it with pthreads ( by setting in the Makefile  MYLIBS="-Wl,-E -pthread -ldl" ), crashes do not occur. If I remove the pthread option, crashes show up. So, maybe the bug is my project configuration after all: I do use pthreads for launching the server threads, which run Lua code, from a C module. So, maybe standard Lua will not do, and I have to use a special build of it. I really do not know Linux kernel well enough to understand why this kind of incompatibility issue could arise. 

Anyway, I hope this information is useful. Thanks for your attention!

backtrace:
 
Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 3266]
__GI_fgets_unlocked (buf=0x7ffff0f47cd0 "0", n=n@entry=880, fp=0x7ffff0f47cd0) at iofgets_u.c:53
53      iofgets_u.c: No such file or directory.
(gdb) bt
#0  __GI_fgets_unlocked (buf=0x7ffff0f47cd0 "0", n=n@entry=880, fp=0x7ffff0f47cd0) at iofgets_u.c:53
#1  0x00007ffff05404ca in get_contents (stream=<optimized out>, len=880, linebuf=0x7ffff0f47cd0 "0") at nss_files/files-XXX.c:201
#2  internal_getent (result=result@entry=0x7ffff0f48190, buffer=buffer@entry=0x7ffff0f47cb0 "0", buflen=buflen@entry=912,
    errnop=errnop@entry=0x7ffff0f49690, herrnop=herrnop@entry=0x7ffff0f48174, af=af@entry=2, flags=flags@entry=0)
    at nss_files/files-XXX.c:246
#3  0x00007ffff0540db9 in _nss_files_gethostbyname3_r (name=0x7fffd40271e8 "milou", af=2, result=0x7ffff0f48190, buffer=<optimized out>,
    buflen=912, errnop=0x7ffff0f49690, herrnop=herrnop@entry=0x7ffff0f48174, ttlp=ttlp@entry=0x0, canonp=canonp@entry=0x0)
    at nss_files/files-hosts.c:141
#4  0x00007ffff0541444 in _nss_files_gethostbyname2_r (name=<optimized out>, af=<optimized out>, result=<optimized out>,
    buffer=<optimized out>, buflen=<optimized out>, errnop=<optimized out>, herrnop=0x7ffff0f48174) at nss_files/files-hosts.c:372
#5  0x00007ffff73db609 in __gethostbyname2_r (name=0x7fffd40271e8 "milou", af=af@entry=2, resbuf=resbuf@entry=0x7ffff0f48190,
    buffer=buffer@entry=0x7ffff0f47cb0 "0", buflen=buflen@entry=912, result=result@entry=0x7ffff0f48188, h_errnop=0x7ffff0f48174)
    at ../nss/getXXbyYY_r.c:266
#6  0x00007ffff73b5c72 in gaih_inet (name=<optimized out>, name@entry=0x7fffd40271e8 "milou", service=<optimized out>,
    req=req@entry=0x7ffff0f48410, pai=pai@entry=0x7ffff0f48268, naddrs=naddrs@entry=0x7ffff0f48264) at ../sysdeps/posix/getaddrinfo.c:586
#7  0x00007ffff73b72cd in __GI_getaddrinfo (name=0x7fffd40271e8 "milou", service=0x7fffd40dfa28 "60617", hints=0x7ffff0f48410,
    pai=0x7ffff0f483d8) at ../sysdeps/posix/getaddrinfo.c:2406
#8  0x00007ffff5c24cf1 in inet_tryconnect (ps=0x7fffd40ee2b8, family=0x7fffd40f0330, address=0x7fffd40271e8 "milou",
    serv=0x7fffd40dfa28 "60617", tm=0x7fffd40f0318, connecthints=0x7ffff0f48410) at inet.c:390
#9  0x00007ffff5c26fc9 in meth_connect (L=0x76bd10) at tcp.c:255
#10 0x00000000004080c0 in ?? ()
#11 0x00000000004115b2 in ?? ()
#12 0x000000000040851d in ?? ()
#13 0x000000000040780b in ?? ()
#14 0x000000000040867b in ?? ()
#15 0x0000000000405dba in lua_pcall ()
#16 0x00007ffff5c25f54 in protected_ (L=0x76bd10) at except.c:107
#17 0x00000000004080c0 in ?? ()
#18 0x00000000004115b2 in ?? ()
#19 0x000000000040851d in ?? ()
#20 0x000000000040780b in ?? ()
#21 0x000000000040867b in ?? ()
#22 0x0000000000405dba in lua_pcall ()
#23 0x00000000004167a8 in ?? ()
#24 0x00000000004080c0 in ?? ()
#25 0x00000000004115b2 in ?? ()
#26 0x000000000040851d in ?? ()
#27 0x0000000000405d25 in lua_call ()
#28 0x000000000041dbea in ?? ()
#29 0x00000000004080c0 in ?? ()
#30 0x00000000004115b2 in ?? ()
#31 0x000000000040851d in ?? ()
#32 0x0000000000405d25 in lua_call ()
#33 0x00007ffff6eb95fb in ?? () from /usr/lib/x86_64-linux-gnu/lua/5.1/thread0.so
#34 0x00000000004080c0 in ?? ()
#35 0x00000000004084d4 in ?? ()
#36 0x000000000040780b in ?? ()
#37 0x000000000040867b in ?? ()
#38 0x0000000000405e45 in lua_cpcall ()
#39 0x00007ffff6eb9635 in ?? () from /usr/lib/x86_64-linux-gnu/lua/5.1/thread0.so
#40 0x00007ffff6cb5c6b in ?? () from /usr/lib/libsdf0.so.0
#41 0x00007ffff6a9e0a4 in start_thread (arg=0x7ffff0f49700) at pthread_create.c:309
#42 0x00007ffff73ca04d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by vesameskanen** [comment]
Some further notes: Lua's thread safety is not discussed much in the Internet, but I managed to find the following link: https://lwn.net/Articles/654762/ . So, while the error is not in Lua itself, but in the C library, it can be addressed by suitable build options.

Consequently, I submitted a bug report to Lua's Debian maintainers, requesting that future packages would be built using -pthread flag.
