### ISSUE TITLE
IPv4/IPv6 agnostic tcp() and udp() functions

### ISSUE THREAD

**Issue by diegonehab** [diegonehab/luasocket#147]
@mwild1, @sam-github, @Florob, @Tieske, can you take a look at branch [agnostic] (https://github.com/diegonehab/luasocket/tree/agnostic)? It is related to issues #83 and #91. It changes tcp() and udp() to leave the family "open". It will be defined at the first call to bind, connect, or sendto(). I am a bit worried about merging this to master before somebody else vetting the change.

**Comment by Florob** [comment]
From a quick first look I have two remarks:
1. Wouldn't it be better to initialize `tcp->sock` to `SOCKET_INVALID` in `tcp_create`, instead of potentially immediately throwing away the created socket later?
2. `tcp()`, unlike `tcp6()`, does not set the IPV6_V6ONLY socket option. It also just occurred to me that we don't set it if `bind()`/`connect()` doesn't succeed on the first `getaddrinfo()` result and we create a new socket. This is likely to cause inconsistent behaviour (though for an agnostic `tcp()` in particular it might actually be fine to leave the choice to the OS).

**Comment by diegonehab** [comment]
1.a Here is one issue. If the user creates a socket object and proceeds to make several calls to setoption(), these calls won't work at all because we don't have a socket. On the other hand, all options will be lost when we create a new socket, so the problem exists already. I don't think there is a way for us to solve it. Maybe we should just make sure the user understands that, unless the socket is bound, there is a chance all options will be lost?

1.b In the case of UDP, maybe we should change sentto() to use inet_pton instead of getaddressinfo, since the function only accepts numeric parameters anyway? 

2. I was going to ask this before: Why do we bother setting IPV6_V6ONLY anyway?

**Comment by Florob** [comment]
We set IPV6_V6ONLY, because there was some agreement that this causes more intuitive behaviour. If this is option is not set the default (at least for wildcard addresses) is to listen to both IPv4 and IPv6 connections on AF_INET6 sockets. Additionally some vendors (IIRC Debian, and at least some Windows versions) set this option by default, which means that the same code would yield different result depending on the platform, if it is not explicitly set.

**Comment by diegonehab** [comment]
OK. Maybe we should move it to socket_create, then?

**Comment by diegonehab** [comment]
inet_trycreate, I mean.

**Comment by Zash** [comment]
This breaks Prosodys DNS library. Not sure how or why yet.

**Comment by Zash** [comment]
Ok, it breaks when used with libevent

**Comment by diegonehab** [comment]
@Zash, can you be more specific? What breaks?

**Comment by Zash** [comment]
The async DNS wrapper (net.dns and net.adns) did not report getting a reply when running with libevent. I haven't gotten further with debugging than that yet.

**Comment by Zash** [comment]
The root cause seems to be that socket.udp() no longer returns a valid socket and that prosody sets up event handlers before it is collapsed from this undecided state, meaning we end up watching an invalid FD.

**Comment by diegonehab** [comment]
The simplest fix is to call udp4() or udp6() on the async DNS wrapper, right? I never used libevent with LuaSocket.

**Comment by Zash** [comment]
I suppose we'll do

``` lua
if not addr:find(":") then
  sock = (socket.udp4 or socket.udp)();
end
```

in order to be backwards compatible.

**Comment by 4L3Xx** [comment]
So what is happening with IPv6 support?  I am still not able to use it.

**Comment by diegonehab** [comment]
How so? People have been using it for a long time.

**Comment by 4L3Xx** [comment]
I am trying to use HTTP function and it is DEFINITELY not working.

**Comment by diegonehab** [comment]
Please post a small, self-contained snippet of code showing the problem.

**Comment by 4L3Xx** [comment]
`
local http = require("socket.http");

response, code = http.request({url = "http://[2607:f8b0:400a:800::200e]"})

print(response)
print(code)
`

`
$ lua test.lua 
nil
Address family for hostname not supported
`

After applying this patch https://github.com/darklajid/luasocket/commit/4785d9e6fcf107721602afbc61352475d56f921a.patch it works perfectly.

Side question: how do you install your version of luasocket?  Your rockspec file references the original repository.

**Comment by diegonehab** [comment]
Works fine with the latest version of the library compiled from the repository.

[diego@fresnel ~] cat a.lua
local http = require("socket.http");

response, code = http.request({url = "http://[2607:f8b0:400a:800::200e]"})

print(response)
print(code)
[diego@fresnel ~] lua53 a.lua
1
404

**Comment by 4L3Xx** [comment]
Is the fix in a release?

**Comment by 4L3Xx** [comment]
So here is what I found.

This installs a working version:
```shell
$ luarocks install https://raw.githubusercontent.com/diegonehab/luasocket/master/luasocket-scm-0.rockspec --local
```

This installs a broken version:
```shell
$ luarocks install luasocket --local
```

It claims it installs 3.0rc1-2 but the test script fails with it.

**Comment by diegonehab** [comment]
I have no experience with Lua rocks. Can you modify the rockspec to get the head from master?

**Comment by moteus** [comment]
That can be done by install scm version
```
 luarocks install luasocket --from=http://luarocks.org/dev
```

**Comment by diegonehab** [comment]
Thanks, moteus!

**Comment by 4L3Xx** [comment]
So, the fix IS NOT in `3.0-rc1`.  I checked it and this IS the case.

@moteus, your suggestion totally DOES NOT work!

```
$ sudo luarocks install luasocket --from=http://luarocks.org/dev
.........
$ lua test.lua 
lua: error loading module 'socket.core' from file '/usr/lib64/lua/luarocks/lib/lua/5.1/socket/core.so':
        /usr/lib64/lua/luarocks/lib/lua/5.1/socket/core.so: undefined symbol: luaL_setfuncs
stack traceback:
        [C]: ?
        [C]: in function 'require'
        /usr/lib64/lua/luarocks/share/lua/5.1/socket.lua:12: in main chunk
        [C]: in function 'require'
        ...usr/lib64/lua/luarocks/share/lua/5.1/socket/http.lua:10: in main chunk
        [C]: in function 'require'
        test.lua:1: in main chunk
        [C]: ?
```

Here is why: [https://luarocks.org/manifests/luarocks/luasocket-scm-1.rockspec](https://luarocks.org/manifests/luarocks/luasocket-scm-1.rockspec) (dev version) is missing compat.c stuff in the rock file.  Compare it to [https://raw.githubusercontent.com/diegonehab/luasocket/master/luasocket-scm-0.rockspec](https://raw.githubusercontent.com/diegonehab/luasocket/master/luasocket-scm-0.rockspec) (which works) to find out why.

@diegonehab, can you please create a new release that has the fix?  I want my users to be able to use my Lua library with an officially released luasocket version that has this fix.  Asking users to install from master branch is kind of risky.

**Comment by diegonehab** [comment]
4L3Xx, you seem to be somewhat overly excited. Moteus is trying to help you get your stuff working. All of us have been using the HEAD for a while without any problems. So you are the one that has to figure out how to get a copy of the code and compile it in your platform. We all agree there should be a release. However, there are still a couple bugs to be fixed before I can release. It would be great if somebody could go over the list of issues and summarize what has to be done.

**Comment by 4L3Xx** [comment]
Hm, I see.  I'll create a pull request for a rockspec file for the next release for whenever you need it.
I wouldn't say I am excited, but I am a bit unimpressed by the state of this useful library.

**Comment by diegonehab** [comment]
Me too. I've been maintaining this library for almost 18 years and never made a dime from it. A few months ago I wrote to the Lua list asking if anybody else wanted to be the maintainer. I'd work in an advising capacity. Nobody volunteered. Within these 18 years, I moved from an undergraduate being advised by Lua's author Roberto Ierusalimschy to being a researcher/professor. I have other pressing matters to deal with. :/

**Comment by 4L3Xx** [comment]
Maybe this project needs something like https://tip4commit.com/.

**Comment by fabled** [comment]
Seems sendto() does not work on address-agnostic udp socket. See: http://bugs.alpinelinux.org/issues/6603

Minimal testcase:
<pre>
$ lua -e 'assert(require("socket").udp():sendto("test", "127.0.0.1", 80))'
lua: (command line):1: refused
stack traceback:
        [C]: in function 'assert'
        (command line):1: in main chunk
        [C]: ?
</pre>

**Comment by diegonehab** [comment]
Isn't this a correct notification that the given port is not open? Doesn't RFC1122 require it?

**Comment by fabled** [comment]
@diegonehab No, the error comes from the fact that no socket is opened from unspecified address-famly .udp() type at: https://github.com/diegonehab/luasocket/blob/master/src/udp.c#L440 and the fact that the sendto() method does not open a socket in https://github.com/diegonehab/luasocket/blob/master/src/udp.c#L172. The actual error comes from https://github.com/diegonehab/luasocket/blob/master/src/usocket.c#L235.

However, docs at https://github.com/diegonehab/luasocket/blob/master/doc/udp.html#L475 indicate that even the unconnected AF_UNSPEC socket supports sendto() by creating a socket of the given address type on first call to sendto().

If the above code is ran with .udp4() no error is returned from lua-socket and things work as they used to. Yes, network level an ICMP error is generated (if no UDP listener is on the given port), but lua-socket will not get it. This ICMP error is returned only via recvmsg()'s control data.

**Comment by ncopa** [comment]
Patch proposed in https://github.com/diegonehab/luasocket/pull/206

**Comment by puck** [comment]
This makes setting the broadcast flag on a UDP socket troublesome. Any suggestions on how to do this in a family agnostic manner?

I've resorted to forcing use of udp4 (when available) now to work around this.

**Comment by pravinkpatel** [comment]
Give option  of inet/inet6 for any connection
