### ISSUE TITLE
Need access to the socket buffer or perhaps a call to 'read' from the socket exclusively for buffered data

### ISSUE THREAD

**Issue by harningt** [diegonehab/luasocket#150]
In LuaSocket, there is an issue that the user may want to read from a socket to get data from the buffer but not want the call out the the underlying recv call to be made.
It seems that in this case - the desire would be the ability to call receive with a flag indicating that 'just' the buffer is desired, no socket call. I think that this would be paired with partial receives to if not all the data is available in the buffer.

Relevant issue harningt/luaevent#6

Proposed API options (unless a raw buffer API is to be exposed eventually):
```lua
client:receive([pattern [, prefix [, isBufferOnly]]])
-- isBufferOnly passed as boolean to indicate buffer-only operation, presumably empty buffer => immediate timeout error?

client:receive([pattern [, prefix]])
-- pattern may be one of
-- "*l" read-line
-- "*a" read as much as possible
-- number read bytes
-- "*bl" read-line only from buffer
-- "*ba" read all of buffer
-- "*bnumber" read number of bytes from buffer
-- alternate option negative number
```

The alteration of what the 'pattern' means can make it so that only buffer.c needs alterations (I believe) and it would carry throughout the protocols vs just a specific kind.

Even if this isn't a solid fix for what the LuaEvent is, I think it would still be useful to pull bytes from the buffer knowing that the network will not be contacted.

**Comment by diegonehab** [comment]
Why not simply set the timeout to zero? If there is data, it will be returned right away.
