### ISSUE TITLE
undefined symbol: lua_pcall

### ISSUE THREAD

**Issue by studentz** [diegonehab/luasocket#152]
Sytem: lsb_relealse -a   Ubuntu 14.01 
            lua -v  5.2.3 
            luarocks 2.2

Installed using luarocks, no error during compilation. Calling the script (example of TCP server) from documentation produce the following error error. 

	/home/user/torch/install/lib/lua/5.1/socket/core.so: undefined symbol: lua_pcall stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/home/user/torch/install/share/lua/5.1/socket.lua:12: in main chunk
	[C]: in function 'require'
	sertcp.lua:2: in main chunk
	[C]: in ?

Thanks

**Comment by siffiejoe** [comment]
> lua -v 5.2.3 
> [...]
> /home/user/torch/install/lib/lua/5.1/socket/core.so: [...]

The "5.1" in the path name indicates that luasocket has been compiled for Lua 5.1. So you can't use it with Lua 5.2.

**Comment by studentz** [comment]
Thanks. sifflejoe
From the torch interpreter
print(_VERSION)   Lua 5.1
From Lua native interpreter 
print(_VERSION)  Lua 5.1

My quick solution was to use torch interpreter in order to run the socket script .

I guess the definitive solution is recompile torch with Lua 5.2. ??

**Comment by ignacio** [comment]
I don't think that would work. Torch is built on LuaJIT.

**Comment by studentz** [comment]
Thanks Ignacio
I will keep the easy way (using th interpreter) :).
I guess we can close this issue, unless there are more suggestions.
