### ISSUE TITLE
ftp Rename

### ISSUE THREAD

**Issue by antonioscuri** [diegonehab/luasocket#154]
To do a ftp rename operation is necessary to perform two commands:  "rename from" and "rename to" in  sequence.

  If I try:

```lua
local function rename_from(u)
    local p = url.parse(u)
    p.command = "rnfr"
    p.argument = string.gsub(p.path, "^/", "")
    if p.argument == "" then p.argument = nil end
    p.check = 250
    return ftp.command(p)
end

local function rename_to(u)
    local p = url.parse(u)
    p.command = "rnto"
    p.argument = string.gsub(p.path, "^/", "")
    if p.argument == "" then p.argument = nil end
    p.check = 250
    return ftp.command(p)
end

ret, err_msg = rename_from(u_from)
print(ret, err_msg)
ret, err_msg = rename_from(u_to)
print(ret, err_msg)
```

 Then I get:

nil     350 RNFR accepted - file exists, ready for destination
nil     503 Need RNFR before RNTO

 The real problem is the first message, which should be ignored and let the second command go on. 

 Then I did an improvement (copied from "ftp.lua"):

```lua
_M.command = socket.protect(function(cmdt)
    cmdt = override(cmdt)
    socket.try(cmdt.host, "missing hostname")
    socket.try(cmdt.command, "missing command")
    local f = _M.open(cmdt.host, cmdt.port, cmdt.create)
    f:greet()
    f:login(cmdt.user, cmdt.password)
    f.try(f.tp:command(cmdt.command, cmdt.argument))

    print("step1")
    if (cmdt.command2) then 
      f.try(f.tp:command(cmdt.command2, cmdt.argument2)) 
    else
      if cmdt.check then f.try(f.tp:check(cmdt.check)) end
    end
    --if cmdt.check then f.try(f.tp:check(cmdt.check)) end
    print("step2")
    f:quit()
    print("step3")
    return f:close()
end)

local function ftp_rename(file_from, file_to)
    local p = socket.url.parse(server.ftp_url..file_from)
    p.user = server.ftp_user
    p.password = server.ftp_password
    p.command = "rnfr"
    p.argument = string.gsub(p.path, "^/", "")
    if p.argument == "" then p.argument = nil end

    local p2 = socket.url.parse(server.ftp_url..file_to)
    p.command2 = "rnto"
    p.argument2 = string.gsub(p2.path, "^/", "")

    p.check = 250
    return socket.ftp.command(p)
end

ret, err_msg = ftp_rename("test.txt", "rename.log")
print(ret, err_msg)
```

  The result:

step1
step2
nil     350 RNFR accepted - file exists, ready for destination

  Never get to step3 because of the error message, but the file was successfully renamed!

  So I would like a clean solution without errors and with a proper close (the access to the server after the error got weird for a while).

  Any ideas?

Thanks in Advance,
Antonio Scuri

**Comment by diegonehab** [comment]
How about this untested code?


    _M.command = socket.protect(function(cmdt)
        cmdt = override(cmdt)
        socket.try(cmdt.host, "missing hostname")
        socket.try(cmdt.command, "missing command")
        local f = _M.open(cmdt.host, cmdt.port, cmdt.create)
        f:greet()
        f:login(cmdt.user, cmdt.password)
        if type(cmdt.command) == "table" then
            local argument = cmdt.argument or {}
            local check = cmdt.check or {}
            for i,cmd in ipairs(cmdt.command) do
                f.try(f.tp:command(cmd, argument[i]))
                if check[i] then f.try(f.tp:check(check[i])) end
            end
        else
            f.try(f.tp:command(cmdt.command, cmdt.argument))
            if cmdt.check then f.try(f.tp:check(cmdt.check)) end
        end
        f:quit()
        return f:close()
    end)

Then you could use something like this:

    ftp.command{
        host = ...,
        user = ...,
        password = ...,
        command = {"RNFR", "RNTO"},
        argument = {from_name, to_name},
        check = {"350", "250"},
    }

Can you try it?

**Comment by antonioscuri** [comment]
Yes. It works.

 I did a debug:

        print("before")
        for i,cmd in ipairs(cmdt.command) do
            f.try(f.tp:command(cmd, argument[i]))
            print("step", i)
            if check[i] then f.try(f.tp:check(check[i])) end
        end
        print("after")

 The output was:

before
step    1
step    2
after

  And the returned values:

1       nil

  The file was sucessfully renamed using ftp.

Thanks,
Scuri

**Comment by diegonehab** [comment]
Cool. I'll document and update it at some point.
