### ISSUE TITLE
Is luasocket thread safe?

### ISSUE THREAD

**Issue by tobiasschweizer** [diegonehab/luasocket#175]
We are developing a [software](https://github.com/dhlab-basel/Sipi) in C++ that makes use of Lua to easily implement some custom functionalities the user may wish to have. The software implements an API to request images in a specified resolution, rotation etc.

In https://github.com/dhlab-basel/Sipi/blob/develop/sipi.init-knora.lua, we implemented a Lua function that is called each time a client makes a request to our API. Each request is handled in a separate thread.

```lua
function pre_flight(prefix,identifier,cookie)

    -- use Sipi's luarocks to install these modules
    requests = require "requests"
    json = require "json"
...
```

We encountered a Lua problem when a lot of requests were made to our API at the same time. The application crashed. However, when we commented out `requests = require "requests"`, all went fine again.

So could it be a problem that `requests` is loaded by separate threads at the same time? Each thread has its own Lua interpreter.

I asked the developer of `lua-requests` about this (https://github.com/JakobGreen/lua-requests/issues/9) and he told me that his module depends on `luasocket` and that the problem could be there.

So I would like to ask you if `luasocket`is thread safe.

**Comment by moteus** [comment]
I think LuaSocket itself is thread safe. But some functions on some system not thread safe.
E.g. `gethostbyaddr` Is not thread safe on POSIX, but it thread safe for Windows. (may be need use `gethostbyaddr_r`).
I did not see any analize of all used functions in LuaSocket but you can take a look at this [discussion](https://github.com/diegonehab/luasocket/issues/144)

**Comment by diegonehab** [comment]
LuaSocket is not thread safe because of buffering on the socket objects. If two threads attempt to read on the same socket, things may go very wrong. There is also the problem that Moteus mentioned. A few of the networking functions we use may or may not be thread safe depending on the OS. One possibility is to try to use the lua_lock and lua_unlock macros surrounding the critical regions to make sure everything is thread safe. Does anyone care to take a stab at it?

**Comment by tobiasschweizer** [comment]
Thanks for your answers!

**Comment by diegonehab** [comment]
Keep in mind that the default macros don't do anything. They must be redefined. LuaThreads used to do this, but there was so little interest that it was discontinued. The problem here is that Lua itself is not thread safe. So there can be only one script running on each Lua context at each time.

**Comment by sonoro1234** [comment]
Would it be thread safe for using two different socket connections, each one in a different lane of lualanes.?
