### ISSUE TITLE
LuaSocket for Symbian 9.2

### ISSUE THREAD

**Issue by Symbian9** [diegonehab/luasocket#180]
Some instruction
- http://www.warmplace.ru/forum/viewtopic.php?t=3548

Related
- http://github.com/instead-hub/instead

**Comment by ewestbrook** [comment]
Would you please state what the actual issue is here, if indeed there is an issue?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!
