### ISSUE TITLE
error loading module 'socket.core' from file ...

### ISSUE THREAD

**Issue by SchoolGuy** [diegonehab/luasocket#185]
Hi guys,

I set up luasocket by hand. The following code I have written to make sure my file can run luasocket.

```
info = debug.getinfo(1,'S');
info = string.gsub(info.source,"@","")
filePath = string.sub(info,1,#info-11)
package.path = package.path..';' .. filePath..'\\luasocket-2.0.2\\lua\\?.lua'
package.cpath = package.cpath..';' .. filePath..'\\luasocket-2.0.2\\?.dll;' .. filePath..'\\luasocket-2.0.2\\mime\\?.dll'
```

This works so far. But then I get the error written in the headline at line 13. The structure where I put the socket lib download unzipped is:
```
Project Folder
              | global.lua
              | luasocket-2.0.2 //with subfolders etc.
```

Hope this is enough information to say if this is a error by your code or my setting.

**Comment by diegonehab** [comment]
We have been using LuaSocket for a while, so I'm pretty sure there is no bug in our way of loading things. Where did you get a zip file? We don't distribute binaries, so you'd have to compile the code...

**Comment by SchoolGuy** [comment]
I'd get the code in a .zip file which I get from the luaforge archived versions page (http://files.luaforge.net/releases/luasocket/luasocket). Why do I have to compile the code? This wasn't appearing to my eyes when reading my set up recommendations at w3.impa.br. (http://w3.impa.br/~diego/software/luasocket/installation.html)

**Comment by diegonehab** [comment]
Which file exactly did you download? There are a bunch of files on LuaForge.

**Comment by SchoolGuy** [comment]
luasocket-2.0.2

**Comment by diegonehab** [comment]
The link luasocket-2.0.2 takes you to another page, where you have luasocket-2.0.2-lua-5.1.2-Win32-vc6.zip, luasocket-2.0.2-lua-5.1.2-Win32-vc8.zip, and luasocket-2.0.2.tar.gz. The first two files, the zip ones, should contain everything you need to use LuaSocket 2.0.2 with Lua 5.1 on Windows. At least that was the mainteiners' intent, I believe. The file is from 2007... The other file, the tar.gz file, contains the source code that you'd have to compile. If you follow that route, then I suggest you get the latest version of the source code from the git repository itself and compile against a newer version of Lua.
