### ISSUE TITLE
bug: *http.request* will add a trailing newline in the response body

### ISSUE THREAD

**Issue by FrancisHe** [diegonehab/luasocket#187]
The real response body:
```
blablabla
```
The response body use `http.request`:
```
blablabla

```

version: lua-socket-3.0-0.10.rc1.el7.x86_64.rpm

**Comment by diegonehab** [comment]
I don't think so. Maybe your server does it?

**Comment by FrancisHe** [comment]
@diegonehab Sorry, I made a mistake.  It is indeed that the server side emit a trailing newline additionally.

**Comment by diegonehab** [comment]
No proboem!
