### ISSUE TITLE
problem with unix socket

### ISSUE THREAD

**Issue by devbp** [diegonehab/luasocket#193]
I am trying to connect to unix scoket server. I have lau 5.2.3- when I use the code below, I get error

attempt to call field 'unix' (a table value)
stack traceback:

socket = require"socket"
socket.unix = require"socket.unix 
c = assert(socket.unix())
assert(c:connect("/tmp/foo"))
    while 1 do
        local l = io.read()
        assert(c:send(l .. "\n"))
    end_

Does lua 5.2.3 support unix socket in lua?

**Comment by diegonehab** [comment]
Yes. We now support stream and dgram methods. The current names are "udp()" and "tcp()" and they live in the table you received in your call to require(), though we should probably change them to "dgram()" and "stream()".

**Comment by diegonehab** [comment]
Maybe @enginix can change it? What do you think?

**Comment by enginix** [comment]
Agree, "dgram()" and "stream()" are better here. I'll change it in a few days, as i am quite busy recently.

**Comment by devbp** [comment]
this works for me now..
local socket = require"socket"
socket.unix = require"socket.unix"
u1 = socket.unix.tcp()
u2 = socket.unix.udp()

assert(u1:connect("./sock"))
    while 1 do
        local l = io.read()
        assert(u1:send(l .. "\n"))
    end

**Comment by diegonehab** [comment]
Good. No hurry. Thanks!

**Comment by tkim5574** [comment]
attempt to index a function value (field 'unix')

The above is the error I get. Is this changed since the patch?

**Comment by diegonehab** [comment]
Works for me.

    Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
    > unix = require"socket.unix"
    > a = unix.dgram()
    > print(a)
    unixdgram{unconnected}: 0x1cf8188

**Comment by tkim5574** [comment]
>Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
>-socket._VERSION
LuaSocket 3.0-rc1
>-unix = require ('socket.unix')
>-unix
function: 0x7fe50850b450
>-a = unix.dgram()
stdin:1: attempt to index a function value (global 'unix')
stack traceback:
	stdin:1: in main chunk
	[C]: in ?

**Comment by tkim5574** [comment]
nvm! There was a problem during the installation. Installing with 'make install-both-unix' worked for me
