### ISSUE TITLE
Segfault for http request 

### ISSUE THREAD

**Issue by devbp** [diegonehab/luasocket#203]
I created a simple https server with self signed certificated. 
It works well with all https://  request.

But when I give http// request, I get segfault with code below.

Any hint where I can improve. I am using lua  5.2.3

local server = assert(socket.bind("*", API_PORT))
-- prevent server from blocking in accept forever and even ignoring signals
server:settimeout(1)
-- find out which port the OS chose for us
local ip, port = server:getsockname()
-- print a message informing what's up
logger.log(logger.INFO, "Listening on "..ip.." port ".. port.." for requests.")
-- loop forever waiting for clients
while 1 do
  -- wait for a connection from any client
  print("waiting  for  client")
  local client = server:accept()
  print("accepting status")
  print(client)
  if client ~=nil then
    print(type(client))
  end
  
  if client then
    local client_ip, client_port = client:getsockname()
    logger.log(logger.DEBUG, "Client " .. client_ip .. " connected on port " .. client_port)
    -- make sure we don't block waiting for this client's line
    client:settimeout(60)
   client,ermsg = ssl.wrap(client, ssl_params)
    print("ssl wrap status")
    print(ermsg)
    client:dohandshake()
   --print("client ip="..client_ip)
   --print("client port="..client_port)
    HEADER = ""  --intintionally global
    BODY = "" --intentionally global
    -- receive the line
    while string.len(HEADER) < 4096 do
      print("before receiving")
      local line, err = client:receive()
       print("line received from client")
       print(line)
       print("receive status")
       print(err)
      if not err then
        print(err)
        if line == "" then
          break
	      else
	      HEADER = HEADER .. line .. "\n"
	       end
      else
	logger.log(logger.ERROR, "Error while receiving header: ".. err)
        request = nil
        HEADER = nil
	     break
      end
    end
    if HEADER then
      local url, params, headers = parse_header(HEADER)
      if headers["Content-Length"] ~= nil and tonumber(headers["Content-Length"]) > 0 then
        BODY = ""
        BODY, err = client:receive(tonumber(headers["Content-Length"]))
	if err ~= nil then
	  logger.log(logger.ERROR, "Error receiving body: "..BODY)
	else
	  params = parse_body(BODY, params)
	end
      end
      local http_status, response_body = handle_request(url, params, headers)
      local http_response = "HTTP/1.1 " ..http_status.."\nConntection: close\nApi-Version: "..request_handler.API_VERSION.."\nContent-Length: " .. string.len(response_body) .. "\n\n" .. response_body
      client:send(http_response)
      logger.log(logger.DEBUG, "Received request", HEADER.."\n"..BODY, http_response)
    end
    -- done with client, close the object
    client:close()
    logger.log(logger.DEBUG, "Client " .. client_ip .. ":" .. client_port .. " connection closed.")
  end
end

**Comment by diegonehab** [comment]
Can you get it to crash without using LuaSec? LuaSec is not ours.

**Comment by devbp** [comment]
if I omit  
client,ermsg = ssl.wrap(client, ssl_params)
print("ssl wrap status")
print(ermsg)
client:dohandshake()

then I dnt get any segfault, but I dnt get https features.

**Comment by diegonehab** [comment]
Can you post the code that segfaults to the LuaSec project?
