### ISSUE TITLE
Not an issue - is there a forum instead?

### ISSUE THREAD

**Issue by jcsayre** [diegonehab/luasocket#205]
Sorry, I am a complete newb to this, and I don't see any forum for me to ask a question. I have an enterprise application that uses Lua (5.1) for scripting purposes. I need to initiate REST API calls (GET, POST, PUT) from Lua, and it seems luasocket is the answer. My understanding is that I need the .dll and .lua files (it's a Windows Server environment), but I am struggling with this. Where should I be asking my questions, other than in the "issues" area, as I know that's not the right place? Thanks in advance.

**Comment by diegonehab** [comment]
That depends entirely on how the enterprise application is set up to use Lua. If it links statically to Lua, you are in bad luck. If it links to Lua as a DLL, then you need to know which runtime was used to build the Lua DLL and use the same runtime while building LuaSocket as a DLL. Then you need to figure out where the application configured Lua to look for external Lua and C modules and place LuaSocket appropriately.
