### ISSUE TITLE
Improve TCP receive function.

### ISSUE THREAD

**Issue by m-masataka** [diegonehab/luasocket#212]
We should not throw away the packet data when receive function return IO_TIMEOUT.
In specific case such as BGP protocol, we need to send or recv message while keeping TCP connection.
But, luasocket can't implement that. 
Because of it has only three receive() options "*l", "*a","[size of buffer]" , and these options can't receive data without connection closed or detect line feed code, (or filled up buffer). 
So, I want to implement the function that fulfill this need.

What do you think about it?

**Comment by moteus** [comment]
Can checkout https://github.com/moteus/luasocket/commit/906774139162c1e21cf88b5178e2305c101322b4
And you are not first one. 
E.g. https://github.com/diegonehab/luasocket/issues/35 and https://github.com/diegonehab/luasocket/issues/105

**Comment by m-masataka** [comment]
Great! Thanks @moteus 
Thanks you for the information and implementation.
