### ISSUE TITLE
url.absolute() can alter hostname when applying relative path

### ISSUE THREAD

**Issue by dev-random** [diegonehab/luasocket#254]
```lua
local url = require 'socket.url'
print(url.absolute('http://example.com/', '../.badhost.com/')
```
Expected: either ```http://example.com/../.badhost.com/``` or ```http://example.com/.badhost.com/```

Got: ```http://example.com.badhost.com/```

**Comment by ewestbrook** [comment]
Fixed in #256.

**Comment by dev-random** [comment]
Stil broken:
```lua
url.absolute("http://example.com/", "...badhost.com")
```
Got: ```http://example.com.badhost.com/```

**Comment by ewestbrook** [comment]
It's still unmerged; could that be why you're not seeing it?  Checking out the branch in progress produces the correct result for me here.

**Comment by dev-random** [comment]
"ewestbrook/luasocket/luasocket254"? That's what I'm testing.
Maybe I should've made it more clear that the test cases in the two posts differ? You did fix the issue in the original post, but introduced an almost identical issue described in the reply.

**Comment by ewestbrook** [comment]
Ah!  Thank you, I overlooked the subtle difference in your second example.  Investigating.

**Comment by ewestbrook** [comment]
Better now, and thanks for testing.  I've also added your examples verbatim to the self-tests to help avoid future regression.

**Comment by dev-random** [comment]
```lua
print(url.absolute("http://example.com/a/b/c/d/", "../../../../q"))
```
Expected: ```http://example.com/q```
Got: ```http://example.com/a/b/q```

**Comment by ewestbrook** [comment]
Got it.  Thanks again, keep 'em coming!

**Comment by dev-random** [comment]
```lua
print(url.absolute("http://example.com", ".badhost.com"))
```
Expected: ```http://example.com/.badhost.com```
Got: ```http://example.com.badhost.com```

**Comment by ewestbrook** [comment]
Nice catch. Fixed as well.

**Comment by dev-random** [comment]
A corner case:
```lua
print(url.absolute("http://example.com/a/b/c/d/", "..//../../../q"))
```
Expected: ```http://example.com/a/q```
Got: ```http://example.com/a/b/c/d/..//../q```

Empty path components are valid components that ".." should be able to remove.

**Comment by ewestbrook** [comment]
Tricky, and indeed, apparently legal.  Fixed.

**Comment by dev-random** [comment]
```lua
print(url.absolute("http://example.com/a/b/c/d/", "..//a/../../../../q"))
```
Expected: ```http://example.com/a/q```
Got: ```http://example.com/a/b/c/q```

**Comment by ewestbrook** [comment]
Fixed, and all prior cases still passing.  Empty path segments are now transformed to special non-empty segments during normalization, then back if any remain.

**Comment by dev-random** [comment]
Numbers (like ```0x00```) get converted to their decimal representations (```'0'```) when used as strings. Also, in Lua52+, hexadecimals can be floating-point, and the period after 0x00 is treated as part of the number. 
```lua
print(url.absolute("http://example.com/", "/0/q"))
```
Expected: ```http://example.com/0/q```
Got:
Lua51: ```http://example.com//q```
Lua52+: ```url.lua:88: malformed number near '0x00..'```

**Comment by ewestbrook** [comment]
I see.  Seeking alternate marker.

**Comment by ewestbrook** [comment]
Perhaps string.char(1) is unambiguous enough.

**Comment by diegonehab** [comment]
Is this all good now? Shall we close the issue?

**Comment by dev-random** [comment]
It seems so. I cannot find any problems now.
