### ISSUE TITLE
Compilation in windows

### ISSUE THREAD

**Issue by NiggaInTheNight** [diegonehab/luasocket#255]
Its very funny and strange process. win32.bat and mingw.bat, open solution in msvs dont work. Before compilation you need read source of bat and make file for understand what happened and do fixes, fixes, fixes...
1) Lua51.props or Lua52.props must be renamed to lua.props.
2) You need add extra path to lua (not luasocket) source.
3) Now it cant compile because compiler saved *.obj to release folder and dont see that files.
4) Why you try to compile luasocket like "debug" in win32?
It just dont work. Try run that before release, pls.
No useful info in readme. Only "Have fun, Diego Nehab". Diego, thx - i got fun, but i dont got luasocket in binary..

**Comment by diegonehab** [comment]
Windows is a pain. There is no distribution system. There is no standard way to make sure you have the needed environment to build LuaSocket. You need to build your own Lua binaries and then modify the Lua.props file accordingly to find the Lua includes and the import library for the Lua DLL. I just pushed a commit that updates the project files to Visual Studio 2017 and verified that it builds fine on my machine.
