### ISSUE TITLE
udp:receive doesn't respect timeout

### ISSUE THREAD

**Issue by softwarefailure** [diegonehab/luasocket#261]
Consider the following code:

```
local socket = require("socket")
udp = socket.udp()
udp:settimeout(10)
udp:receive(1024)
```

This returns immediately although there is no data to receive and the timeout has been set to 10 seconds. Shouldn't it wait 10 seconds first? 

The doc on `udp:settimeout()` says that `udp:receive()` will block or respect the timeout:

> By default, the receive and receivefrom operations are blocking. That is, any call to the methods will block indefinitely, until data arrives. The settimeout function defines a limit on the amount of time the functions can block. When a timeout is set and the specified amount of time has elapsed, the affected methods give up and fail with an error code.

But this doesn't work either. When using this code

```
local socket = require("socket")
udp = socket.udp()
udp:receive(1024)
```

`udp:receive()` doesn't block at all. Instead it exits immediately. Shouldn't it block forever according to the docs?

Tested on Windows 7.

**Comment by diegonehab** [comment]
Not necessarily. This udp socket is not bound to any address. So how could it receive anything? Is it reporting a timeout or is it returning a different error?

**Comment by softwarefailure** [comment]
Oops, right, adding `udp:setsockname("*", 0)` makes it work as I'd expected.
