### ISSUE TITLE
[BUG] LuaSocket is not thread safe

### ISSUE THREAD

**Issue by ewestbrook** [diegonehab/luasocket#274]
Pasted from the Lua mailing list:

> From: Viacheslav Usov <via.usov@gmail.com>
> Date: Sat, 9 Mar 2019 12:53:52 +0100
> Subject: [BUG] LuaSocket is not thread safe
> 
> With this grand opening title, I would like to attract attention to the following problem in mime.c:.
> 
> Function luaopen_mime_core that is called when the mime module is required, calls function b64setup, which initialises a static (global) array b64unbase. It does this as follows:
> 
> static void b64setup(UC *unbase)
> {
>     int i;
>     for (i = 0; i <= 255; i++) unbase[i] = (UC) 255;
>     for (i = 0; i < 64; i++) unbase[b64base[i]] = (UC) i;
>     unbase['='] = 0;
> }
> 
> Observe that the first loop fills the entire array with byte value 255, then certain elements within the array are overwritten with some other values. Those other values are expected in mime.unb64.
> 
> In an application that hosts multiple Lua states this function will be called multiple times if code in multiple states requires mime. If the states run in concurrent threads, these calls may execute concurrently, too, and then can also run concurrently with the code that calls mime.unb64, which may see the incorrect byte value 255 set up by the first loop. There is no simple way to reproduce this except by using a debugger to freeze and thaw threads in the right places.
> 
> There are multiple ways to fix that, but perhaps it is best to initialise those arrays statically, because running the init code multiple times does not make much sense.
> 
> Cheers,
> V.

**Comment by diegonehab** [comment]
One way to satisfy this use case is to simply use a static storage constant  initializer. Another is to use c++11 magic statics.

**Comment by ewestbrook** [comment]
I used static const data in my [LuaBase64](https://github.com/ewestbrook/LuaBase64) example project.  Because it has distinct C functions for initialization, update, and finalization functions, and also uses a typed userdatum for state, it also supports LTN12 streaming.  I'd like to take a stab at duplicating that code here, while providing exactly compabitle API calls for existing callers.  PR to come.

**Comment by diegonehab** [comment]
Is there a reason to do anything more complicated than an initializer? The code in mine seems good enough for most purposes. Unless I'm missing something.

**Comment by ewestbrook** [comment]
I find yours a little harder to follow, but sure, that ought to be fine.  Maybe we can just make that data static const, and while we're at it add something like `ltn12.filter.base64enc` and `ltn12.filter.base64dec`.

**Comment by ewestbrook** [comment]
I take that back -- it's just not as familiar to me (lol).  I'll see what I can wrangle.

**Comment by diegonehab** [comment]
I agree it's not as simple as possible. But when you consider the requirement for it to maintain as little context as possible between invocations, it's what I could come up with. :) Let me see if I can expand that loop.

**Comment by diegonehab** [comment]
Can you check branch mime-static?

**Comment by ewestbrook** [comment]
Checking now

**Comment by ewestbrook** [comment]
Works here.

```
$ lua <<<"mime=require'mime'; ltn12=require'ltn12'; sink,t=ltn12.sink.table(); ltn12.pump.all(ltn12.source.string'This is an encoding test', ltn12.sink.chain(mime.encode'base64', sink)); print(table.concat(t))"
VGhpcyBpcyBhbiBlbmNvZGluZyB0ZXN0
```

```
$ lua <<<"mime=require'mime'; ltn12=require'ltn12'; sink,t=ltn12.sink.table(); ltn12.pump.all(ltn12.source.string'VGhpcyBpcyBhbiBlbmNvZGluZyB0ZXN0', ltn12.sink.chain(mime.decode'base64', sink)); print(table.concat(t))"
This is an encoding test
```

```
$ lua mimetest.lua 
testing identity: ok
testing b64 chained encode: ok
testing b64 padding: ok
testing b64 low-level: ok
testing qp encoding and wrap: ok
testing qp encoding and wrap: ok
done in 0.02s
```

**Comment by diegonehab** [comment]
Cool. I'll tweak the formatting and push.

**Comment by ewestbrook** [comment]
Nice.  Thanks!
