### ISSUE TITLE
Update SCM rockspec in the luarocks site.

### ISSUE THREAD

**Issue by moteus** [diegonehab/luasocket#279]
On luarocks site SCM rockspec does not containg `compat.c` file.

**Comment by ewestbrook** [comment]
Done.  See also #280.  New rockspec is version scm-2 and available via [LuaRocks](https://luarocks.org/modules/luasocket/luasocket).

Please let me know if you are successful.  Appreciate your help!

**Comment by moteus** [comment]
It works. But I do not see any reason to create new rockspec here.
SCM rockspec is  a moving target and should match to the current master.
Also may be move it to rockspec directory in the repo

**Comment by ewestbrook** [comment]
Good call.  The PR above does move it to the rockspec directory.

What luarocks command did you use to install?  This did not seem to work for me:

```
# luarocks install luasocket scm-2
Error: No results matching query were found.
```

I was only able to get it installed with:

```
luarocks install https://raw.github.com/diegonehab/luasocket/master/luasocket-scm-0.rockspec
```

(Which will be a deprecated URL shortly.)

**Comment by moteus** [comment]
`luarocks install luasocket --from https://luarocks.org/dev`
Install dev version

**Comment by ewestbrook** [comment]
Nice!  (I had to use `--server` instead of `--from`, maybe because my version of luarocks isn't the latest.)

Now everyone who wants to install the latest `master` via luarocks can do so easily.  Thanks again for helping with this.
