### ISSUE TITLE
How to compile on windows?

### ISSUE THREAD

**Issue by martmists** [diegonehab/luasocket#283]
The win64.cmd does not work, as the syntax is clearly designed for bash

**Comment by diegonehab** [comment]
Use git-bash or the visual studio project files?

**Comment by martmists** [comment]
git bash doesn't have `make` and I couldn't locate a package manager, and visual studio is too big for the remaining disk space I have. I tried the windows version of `make` but that didn't work either.

**Comment by diegonehab** [comment]
Buy a bigger hard drive or use Google to find a make that works inside git bash.

**Comment by martmists** [comment]
I got windows make working under bash with the same issue.

**Comment by diegonehab** [comment]
I don't know what windows make is. If you mean nmake, it's not compatible.  The first link when I google "git-bash make" brings up this: 

    Go to https://sourceforge.net/projects/ezwinports/files/
    Download make-4.1-2-without-guile-w32-bin.zip (get the version without guile).
    Extract zip.
    Copy the contents to your Git\mingw64\ merging the folders, but do NOT overwrite/replace any existing files.

This is what I used. Please try to be more resourceful.

**Comment by martmists** [comment]
Now it's complaining about lua.h missing?

**Comment by martmists** [comment]
Finally got it working somehow, but now the module won't load:
```
error loading module 'socket.core' from file '.\socket\core.dll':
	The specified module could not be found.

script stopped.
```

**Comment by diegonehab** [comment]
Read about how Lua looks for modules. Then make sure LuaSocket has been installed where your Lua installation looks for files.

I am assuming there is something that stops you from using LuaRocks...

**Comment by martmists** [comment]
There is; I'm trying to use this within the DesMuMe emulator. After a bunch of trial and error I figured out the lua5.1.dll had to not only be in DesMuMes directory but also where socket.lua was

**Comment by diegonehab** [comment]
It's more like the other way around. Check package.path and package.cpath.
