### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GildedHonour** [diegonehab/luasocket#284]
How to install it?

Where is documentation?

**Comment by diegonehab** [comment]
Use luarocks. No?

**Comment by GildedHonour** [comment]
`
luarocks install <who knows what the what the proper name this library is> 
`

where is the documentation in the first place, any link to it in the repo ?

**Comment by GildedHonour** [comment]
?

**Comment by diegonehab** [comment]
Have you tried luasocket?

**Comment by GildedHonour** [comment]
No!

**Comment by GildedHonour** [comment]
Diego!

**Comment by GildedHonour** [comment]
Diego! I'm your real father!
