### ISSUE TITLE
Broadcast udp:sendto

### ISSUE THREAD

**Issue by BLLuis** [diegonehab/luasocket#339]
A long time ago I wrote a lua script to send a magic packet to Wake On Lan one of my servers, for years have been working good but now I copy that script to another device, one with three ip address and have error with sendto, why, because magic packet needs to be sent to 255.255.255.255 and with this address the sendto don't know what interface to use, I don't even can use 192.168.2.255 (local subnet broadcast) because NIC's wait for full broadcast address.

This is part of my code:
`local broadcastAddr = "255.255.255.255";`
`local mac = "ad:fa:32:23:43:blah:blah:blah";`
`local udp = require("socket").udp();`
`udp:settimeout(1);`
`udp:setoption("broadcast", true);`
`local data1,data2 = udp:sendto(string.char(0xff):rep(6) .. mac:rep(16) , broadcastAddr, 9);`

This code snippet works well on a single IP address device but not on multiple IP address.
Is there any way to set the socket to go on some NIC but still send the packet to 255.255.255.255 as the WOL needs?

Thanks in advance

**Comment by azdle** [comment]
Does binding the socket to the local IP on that interface give it enough info? I haven't done much with broadcast, but I would expect that to work.

If you don't know the interface IP, you can get the kernel to tell you what it is by "connecting" a udp socket to a device you know is on that network:

```
function find_interface_ip_for_remote(ip)
  local s = socket:udp()
  s:setpeername(ip, 9) // 9 is the "discard protocol", doesn't actually matter tho will send no data
  local localip, _, _ = s:getsockname()

  return localip
end
```

**Comment by BLLuis** [comment]
Thanks for your answer, after device firmware upgrade (SmartTV), it parse the magic packet using the local subnet broadcast (192.168.1.255), so, it works as expected.
