### ISSUE TITLE
Best way to check for tcp alive-ness and also question about timeout.

### ISSUE THREAD

**Issue by greatwolf** [diegonehab/luasocket#98]
What's the best way to check if the server end-point is closed or not for a given tcp object, preferably in a non-blocking fashion?

Currently I'm doing something like this:

    local function isalive (tcp)
      tcp:settimeout (0)
      return not (tostring(tcp.sock):match "closed")
               and socket.skip (1, tcp:receive "*a") ~= "closed"
               and tcp
    end

But I'm not sure if this solution is problem-free. A thing I don't like is that `tcp:settimeout` has to be called to ensure `tcp:receive` doesn't cause an indefinite block and the old timeout isn't getting restored after the fact.

This brings me to my next question, is there some way to save the old timeout, eg. `tcp:gettimeout()` so that it can be restored afterwards? Or perhaps have `tcp:settimeout` return the old timeout instead of 1?

Thanks!

**Comment by diegonehab** [comment]
Not sure how to check if a server is remote on the other end. But you can find out if the local side is closed by calling getfd() and comparing the result with "socket._SOCKETINVALID".

Also added the gettimeout you were looking for.
